[package]
name = "geyser-grpc-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tonic = "0.12"
prost = "0.13"
yellowstone-grpc-proto = "8.0"
yellowstone-grpc-client = "8.0"
solana-sdk = "2.0"
futures = "0.3"
